ignore:
  - "pypro/base/migrations"
  - "pypro/base/models.py"
  - "pypro/base/admin.py"
  - "pypro/aperitivos/views.py"
  - "pypro/aperitivos/models.py"
  - "pypro/aperitivos/tests/"
  - "pypro/modulos/tests"