# Generated by Django 3.2.4 on 2021-06-25 01:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='matriculas',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
