# Generated by Django 3.2.4 on 2021-06-22 18:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("modulos", "0007_vimeo_obrigatorio"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aula",
            old_name="vimeo_id",
            new_name="youtube_id",
        ),
    ]
