# Generated by Django 3.2.4 on 2021-06-22 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aperitivos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='vimeo_id',
            new_name='youtube_id',
        ),
    ]
